### ISSUE TITLE
How to run step by step 

### ISSUE THREAD

**Issue by vanlong99hsgs** [dan-marshman/denki-uc#1]
Dear sir, 

First, thank you for dedicating your time to response.
I was wondering if you could possibly help me to explain how can I run this code step by step.

Thank you once again.
Regards, 
Long

**Comment by seagulljim** [comment]
Hi Long,

You can execute the main.py file to run the code.  However, whilst the code does run, I still adding many of the anticipated features, and expect to have a proper release in the coming weeks.  Thanks.

**Comment by vanlong99hsgs** [comment]
Hello again, 
I have tried to execute the main.py and there is an error:

**runfile('F:/denki-uc-master/main.py', wdir='F:/denki-uc-master')

-------------------------------------------------------------------------

Initiating UC model called test1
Using database folder located at    F:\Users\danie\Documents\denki-uc\input_dbs\test1
Inputs path does not exist. Exiting**

I think the problem related to the folder that I saved your code. Do you have any suggestions for me?
Thank you for responding me.

**Comment by dan-marshman** [comment]
Hi Long,
I've updated the code, and added instructions to install the package on the repository page and README.  
I'm adding documentation to better explain how to use the package.  
Could you let me know if you can run main.py successfully, and I will close the issue. Thanks
