### ISSUE TITLE
Stochastic model results

### ISSUE THREAD

**Issue by Mostafa494** [dan-marshman/denki-uc#3]
Dear Dr. Marshman

Thank you for your efforts.
Please guide me through the following:
1- How to extract the Stochastic model results, as I want to check for each scenario the values of load and renewables?
2- Why the value of objective function is only have one result while I have used for example 3 scenarios, this means that I will have a value of each objective function for each scenario?
3- I have my own country system data, could I use the model and enter this data to produce results include different load and renewable scenarios?

Many many Thanks

**Comment by dan-marshman** [comment]
@Mostafa494 ,
1) If you look in the dispatch.csv file, the values of electricity demand, dispatch of generators, and so on, is available, across all intervals and scenarios.  There is also a power_generated.csv output file.  
2) The objective function reported at the command line is the total objective, with a probability of each scenario.  I think it would be useful to have an output which shows what the objective function would be in each individual scenario - I will look at adding this over the next few days.  
3) Yes sure. You would need to edit the input files (demand.csv, wind.csv, solar.csv) as well as unit_data.csv.  You may also want to change the inertia/reserve requirements or set them to zero.  Note that I am still adding some constraints for different generation technology types - in particular I have not yet added longer term storage (e.g. pumped hydro).  This is on my to do list.
